### ISSUE TITLE
A long first word in site title bumps against search box

### ISSUE THREAD

**Issue by patrickmj** [charvolant/bigstuff#1] opened 2015-12-22 20:51 UTC
Make a site title something like "Collections of dev", and "Collections" extends under the search box. 

It'll always be possible for people to create titles that cause this, but "Collections" seems likely enough among Omeka sites for it to be a worry. Smaller size for the site title, or a configuration option to adjust it would likely alleviate the issue.

(Firefox also seems to have problems displaying the font, but that's another thing)

**Comment by charvolant** [comment] 2015-12-31 06:22
Font size fixed in https://github.com/charvolant/bigstuff/commit/db347f337445994dd8aa59b109214f8e20594058

I've been unable to reproduce the font display problem on Firefox, Chromium and IE. It's using standard Google Fonts, so if you can supply me with a screenshot and/or error console log I can see what's going wrong.

**Comment by patrickmj** [comment] 2015-12-31 18:28
That fix seems to work better. Here's before and after screenshots in Chromium. Looks the same in FF.

Thanks!

![bigstuff-before](https://cloud.githubusercontent.com/assets/153262/12067120/37be20d6-afc2-11e5-8e61-769e08a62c7b.png)

![bigstuff-after](https://cloud.githubusercontent.com/assets/153262/12067123/40f0be7a-afc2-11e5-9842-807318c08a89.png)

**Comment by charvolant** [comment] 2016-01-01 00:37
No worries.

**Closed by charvolant** 2016-01-01 00:37 UTC
Labels: bug
